name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        
    - name: Install dependencies for inventory service
      run: |
        cd inventory_service
        pip install -r requirements.txt

    - name: Run unit and integration tests for inventory service
      run: |
        cd inventory_service
        pytest

    - name: Install dependencies for order service
      run: |
        cd order_service
        pip install -r requirements.txt

    - name: Run integration tests for order service
      run: |
        cd order_service
        pytest
